# Generated by Django 4.2.17 on 2026-02-28 19:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("rule", models.JSONField()),
                ("valid_words_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("word", models.TextField(unique=True)),
            ],
            options={
                "ordering": ["word"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("duration_seconds", models.PositiveIntegerField(default=60)),
                ("target_words", models.PositiveIntegerField(default=21)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("submitted", "Submitted"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("current_ordinal", models.PositiveIntegerField(default=1)),
                ("total_score", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("time_left_ms", models.IntegerField(blank=True, null=True)),
                ("prompts", models.JSONField(default=dict)),
                ("answers", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="game_sessio_created_1527c6_idx"),
                    models.Index(fields=["status"], name="game_sessio_status_f6c0fe_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("player_name", models.CharField(max_length=64)),
                ("score", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entry",
                        to="game.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["-score", "created_at"], name="game_leader_score_7d1d19_idx"
                    )
                ],
            },
        ),
    ]
