# Generated by Django 4.2.17 on 2026-02-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="prompts",
            field=models.JSONField(default=list),
        ),
    ]
